pub_hdrs = hxx{**}

./: $pub_hdrs

# Install into the tgbot/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/tgbot/
  install.subdirs = true
}
